### PR TITLE
Miscellaneous modernization and cleanup

### PR DESCRIPTION
**Pull request by NotMyFault**
To be merged after https://github.com/jenkinsci/beer-plugin/pull/10, preferably, to build upon its preliminary updates.

### CODE REVIEW

**Comment by timja** [comment]
Conflicts, did you want to enable CD as well?

**Comment by NotMyFault** [comment]
> Conflicts, did you want to enable CD as well?

According to the RPU, CD is not enabled atm, but once change I can surely include it in this PR.

**Comment by timja** [comment]
> > Conflicts, did you want to enable CD as well?
> 
> According to the RPU, CD is not enabled atm, but once change I can surely include it in this PR.

Feel free to enable :D

**Comment by NotMyFault** [comment]
There we go 👏🏻

**Pull request merged**
